just like "job_18_ubuntu-24_04-arm" +sudo /etc/init.d/postgresql stop

diff --git a/.github/workflows/RISC_V_install_R.yml b/.github/workflows/RISC_V_install_R.yml
--- a/.github/workflows/RISC_V_install_R.yml
+++ b/.github/workflows/RISC_V_install_R.yml
@@ -7,26 +7,62 @@ on:
    workflow_dispatch:
 
 jobs:
-
   job_master_ubuntu-24_04-riscv:
     name: PG master ubuntu-24.04-riscv
     runs-on: ubuntu-24.04-riscv
+    env:
+      PG: 18
     steps:
+      - name: Echo site details
+        run: echo PG $PG
+
       - name: Echo site details
         run: echo building master
  
       - name: Checkout code
         uses: actions/checkout@v6
 
-      - name: Checkout
+     - name: Before Script
         run: |
           set -x -v -e
+          echo "Minimal"
+          uname -m
+          uname -a
+          cat /proc/cpuinfo
+          cat /etc/os-release
+          set +x +v +e
+          echo Building plr with PostgreSQL $PG
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+          sudo apt-get update -qq
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+          sudo apt-get install -qq r-base-dev acl
+          sudo R --version
+          # Seems PG does not come pre-installed
+          sudo /etc/init.d/postgresql stop
+          sudo apt-get remove --purge postgresql\*
+          sudo rm -rf /etc/postgresql /var/lib/postgresql
+          sudo apt-get install postgresql-$PG
+          sudo apt-get install postgresql-server-dev-$PG
+          echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
+          # Builds under "runner"
+          # Github Actions require elevated priviledges
+          # sudo setfacl -Rm u:postgres:rwx,d:u:runner:rwx /home/runner
+          sudo pg_ctlcluster $PG main reload
 
-          sudo apt update
-          sudo apt-get upgrade -y
-          sudo apt-get install -y r-base r-base-dev
-          
-          R --version
-          ldd $(which R)
+      - name: Script
+        run: |
+          sudo pg_lsclusters
+          export USE_PGXS=1
+          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+          sudo USE_PGXS=1 make install
+          /usr/lib/postgresql/$PG/bin/pg_config
+          make installcheck PGUSER=postgres || (cat regression.diffs && false)
 
-#         sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
+      - name: After Success
+        # success() returns true, when none of the previous steps have failed or been canceled.
+        if: ${{ success() }}
+        # Uploads code coverage to codecov.io
+        run: bash <(curl -s https://codecov.io/bash)
